---
# Run all tests
default:
  image:
    name: leandelivery/docker-ansible-ci:ansible-2.9

stages:
  - lint
  - deployment test

before_script:
  - ansible --version
  - ansible-lint --version
  - molecule --version

variables:
  GET_SOURCES_ATTEMPTS: "5"

Lint:
  stage: lint
  before_script:
    - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  script:
    - yamllint . -c .yamllint
    - ansible-lint . -c .ansible-lint
  after_script:
    - rm -rf ~/ansible-lint-rules
  tags:
    - lint

Docker jenkins-slave:
  stage: deployment test
  script:
    - molecule test -s default
  tags:
    - aws

AWS jenkins-slave:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct
  tags:
    - aws

AZURE jenkins-slave-win:
  stage: deployment test
  script:
    - molecule test -s cloud-azure-direct-win
  tags:
    - azure
