-   id: validate_config
    name: Validate Pre-Commit Config
    description: This validator validates a pre-commit hooks config file
    entry: pre-commit-validate-config
    language: python
    files: ^\.pre-commit-config\.yaml$
-   id: validate_manifest
    name: Validate Pre-Commit Manifest
    description: This validator validates a pre-commit hooks manifest file
    entry: pre-commit-validate-manifest
    language: python
    files: ^(\.pre-commit-hooks\.yaml|hooks\.yaml)$
