---
language: python
python:
#  - 2.7
#  - 3.3
#  - 3.4
#  - 3.5
  - 3.6
services:
  - docker
cache:
  bundler:
  directories:
    - $HOME/.cache/pip
env:
  global:
    - JENKINS_HOME=/home/jenkins
    - UID=3000
    - GID=3000
    - secure: MD73NCVzctbVmi2QnQtwtH/ISXN2K0alsLbixoaXl7gr3XvTB4sYB0u+KKtPV46jbeAlQqTRObPfQouPrsLsiNDYcpuN0I5bKsn3TTs4ZHIkD0I2Q9Wh3qNM2fYf9mw3ZUhvXVTEod0W7jzkVGb6kitRCJj8rioKKzvE/YdVsG4=
  matrix:
#  - ANSIBLE_VERSION=latest
    - ANSIBLE_VERSION=2.7.2
sudo: required
dist: trusty
branches:
  only:
  - master
virtualenv:
  system_site_packages: false
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install curl
  - sudo apt-get install -qq python-apt python-pycurl
install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Prepare tests
  # Add user jenkins to the image
  - id -a
  - getent passwd 3000
#  - groupadd -g ${GID} docker && \
  - adduser --quiet --uid ${UID} --gid ${GID} --home ${JENKINS_HOME} jenkins
  # Set password for the jenkins user (you may want to alter this).
  - echo "jenkins:jenkins1234" | chpasswd

  - pip install molecule

  # Update Ansible submodule.
  - git pull && git submodule init && git submodule update && git submodule status
  - git submodule foreach git checkout master

  - ansible-galaxy install -r requirements.yml -p ./roles/ --ignore-errors

script:
  # Check ansible version
  - ansible --version

  # Check syntax
  - ansible-playbook -i ./hosts --syntax-check ./jenkins-slave.yml -vvvv --connection=local -e "python_versions=[2.7, 3.5]" -e "docker_gid=${GID}" -e "jenkins_id=${UID}" -e "python_enabled=false"

  # Molecule test
  # - molecule test

  # First run
  # Run the role/playbook with ansible-playbook.
#  - travis_wait 30
  - ansible-playbook -i ./hosts ./jenkins-slave.yml --connection=local -vvvv -e "python_versions=[2.7, 3.5]" -e "docker_gid=${GID}" -e "jenkins_id=${UID}" -e "python_enabled=false"

  # Run the role/playbook again, checking to make sure it's idempotent.
#  - >
#    ansible-playbook -i hosts jenkins-slave.yml --connection=local -vvvv -e "python_versions=[2.7]"
#    | grep -q 'changed=0.*failed=0'
#    && (echo 'Idempotence test: pass' && exit 0)
#    || (echo 'Idempotence test: fail' && exit 0)

  - id -u jenkins | grep -q "no" && (echo "user not found" && exit 1) || (echo "user found" && exit 0)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    recipients:
      - alban.andrieu@nabla.mobi
    on_success: [always|never|change]         # default: change
    on_failure: [always|never|change]         # default: always
