---
#
# integration-tests.yml
#

- hosts: all
  sudo: true
  tasks:
    # Tests
    - name: Check git
      command: which git
      register: git_path
    - debug: msg="Git was installed in {{git_path.stdout}}"
    - fail: msg="Git not found, tests failed."
      when: git_path.stdout != "{{shell_git_path}}/git"
