---

#- name: Apply hostname configuration
#  hosts: all
#  remote_user: root
##  connection: local
#
#  roles:
#    - alban.andrieu.hostname

#- name: Install git
#  hosts: all
#  sudo: true    
#  remote_user: root
##  connection: local
#
#  roles:
#    - role: geerlingguy.git
#
#- name: Install subversion
#  hosts: all
#  remote_user: root
##  connection: local
#
#  roles:
#    - role: alban.andrieu.subversion
#
#  vars:
#      user: root
#      home: /root
#      subversion_owner_home: "/root/.subversion"
#      subversion_previous_enabled: true   
#      subversion_previous_codename: precise
#      subversion_rabbitvcs_enabled: no
#      subversion_diff_enabled: no
#      subversion_major    : '1'
#      subversion_minor    : '6'
#      subversion_revision : '17'
#      subversion_version : "{{subversion_major}}.{{subversion_minor}}.{{subversion_revision}}"
#      subversion_ubuntu: '{{ subversion_version }}dfsg-3ubuntu3'
      
- hosts: all
  sudo: true  
  remote_user: root
  
#  vars_files:
#  - [ "vars/{{ ansible_distribution }}-{{ ansible_architecture }}.yml", "vars/{{ ansible_distribution }}.yml" ]
    
  roles:
    - { role: ./,
        docker_files_enable: no,
        #jenkins_jdk7_enable: yes,
        user: root,
        home: /root,
        subversion_owner_home: "/root/.subversion",
        subversion_previous_enabled: true,
        subversion_previous_codename: precise,
        subversion_rabbitvcs_enabled: no,
        subversion_diff_enabled: no,
        subversion_major    : '1',
        subversion_minor    : '6',
        subversion_revision : '17',
        subversion_version : "{{subversion_major}}.{{subversion_minor}}.{{subversion_revision}}",
        subversion_ubuntu: '{{ subversion_version }}dfsg-3ubuntu3',
      }

#- name: Install xvbf
#  hosts: all
#  sudo: true    
#  remote_user: root
##  connection: local
#
#  roles:
#    - alban.andrieu.xvbf
