#sudo ansible-playbook -i hosts-albandri -c local -v python.yml --limit albandri.misys.global.ad --ask-pass | tee setup.log

- hosts: all
  gather_facts: true
  tasks:
    - name: group hosts by distribution
      group_by: key="{{ ansible_distribution }}-{{ ansible_distribution_version }}"

- hosts: RedHat-7*:RedHat-6*:RedHat-5*:CentOS-7*:CentOS-6*:Ubuntu-17*:Ubuntu-16*:Ubuntu-14*:Ubuntu-13*:Ubuntu-12*
  gather_facts: false
  tasks:
    - name: group hosts for supported distributions
      group_by: key="supported"

- hosts: "!supported"
  gather_facts: false
  tasks:
    - name: fail for unsupported distribution
      fail: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}
                 is not a supported OS for a Tower installation.  Supported
                 OSes include Red Hat Enterprise Linux 6/7, CentOS 6, or
                 Ubuntu 12.04/13.04/14.04/16.04/17.04."
    - debug: msg="Version {{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_architecture }}"

- name: Install python
  hosts: Ubuntu-12*:Ubuntu-13*:Ubuntu-14*:Ubuntu-16*
  become: yes
  ignore_errors: yes

  roles:
    - python

  vars:
      python_versions: [2.7, 3.5]
      python_install: [numpy, pylint, pandas]
      python_virtualenvs:
        - path: /opt/ansible/env
          python: python2.7
#        - path: /opt/ansible/env36
#          python: python3.6
        - path: /opt/ansible/env35
          python: python3.5
        - path: /opt/scons/env
          python: python2.7

- name: Install python
  hosts: RedHat-7*:RedHat-6*:RedHat-5*:CentOS-7*:CentOS-6*
  become: yes
  ignore_errors: yes

  roles:
    - python

  vars:
      python_versions: [2]
      python_pkg_bin: /bin
      python_bin: /bin/python
      python_virtualenvs:
        - path: /opt/ansible/env
          python: python2.7
#        - path: /opt/ansible/env36
#          python: python3.6
#        - path: /opt/ansible/env35
#          python: python3.5
        - path: /opt/scons/env
          python: python2.7
