
- name: jenkins-slave | Install debug tools
  action: "{{ ansible_pkg_mgr }} name={{ item }} update_cache=yes state={{ jenkins_pkg_state|default('present') }}"
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat')
  with_items:
    - xclock
  become: yes
  ignore_errors: true     
  changed_when: false

#TODO
#sudo yum groupinstall 'Development Tools'

#TODO homebrew
#sudo apt-get install build-essential curl file git python-setuptools ruby
#sudo yum install curl file git irb python-setuptools ruby
#ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
