
- name: Fail if using python3 with Ansible<2.3
  fail:
    msg: "Ansible 2.3+ is required to use Python3 interpreter."
  when: ansible_version.full | version_compare('2.3', '<') and ansible_python_interpreter is defined and 'python3' in ansible_python_interpreter
  
- name: jenkins-slave | Install Ansible (Debian based)
  pip: name={{ item }}
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  with_items:
    - ansible==2.3.0.0
  become: yes

- name: jenkins-slave | Uninstall docker-py
  pip: name=docker-py state=absent
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (ansible_distribution_version in ['16.04'])
  become: yes

- name: jenkins-slave | Install Docker/Ansible compatible tools (Debian based)
  pip: name={{ item }}
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  with_items:
    - docker-compose==1.12.0
    - docker==2.2.1
  when: ansible_version.full | version_compare('2.3', '>=')    
  become: yes

- name: jenkins-slave | Create a docker group
  group:
      name=docker
      state=present
  become: yes

- name: jenkins-slave | Add user(s) to docker group
  user:
      name={{ item }}
      group=docker
      state=present
  with_items: docker_users
  when: docker_users is defined
  become: yes

#sudo gpasswd -a ${USER} docker
#sudo gpasswd -a jenkins docker
