
#sudo pip2 install ansible==2.1.1
#sudo pip2 install docker-py==1.9.0
#ansible 2.3.0 issue and docker-py 2.3.0 issue

#for docker-compose version 1.9.0 and docker version 1.12.6
#sudo pip2 install docker-compose==1.9.0
#sudo pip2 install docker-py==1.10.6
#sudo pip2 install docker==2.0.2
#sudo pip2 install ansible==2.2.0
#sudo pip show docker-py
#- name: jenkins-slave | Install Docker tool (Debian based)
#  pip: name={{ item }}
#  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
#  with_items:
#    - docker-py==1.10.6
#  become: yes

#- name: jenkins-slave | Uninstall docker-py
#  pip: name=docker-py state=absent
#  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (ansible_distribution_version in ['16.04'])
#  become: yes

- name: jenkins-slave | Install Docker/Ansible compatible tools (Debian based)
  pip: name={{ item }}
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (ansible_version.full | version_compare('2.3', '>='))
  with_items:
    - docker-compose==1.12.0
    - docker==2.2.1
  become: yes

- name: jenkins-slave | Create a docker group
  group:
      name=docker
      state=present
  become: yes

- name: jenkins-slave | Add user(s) to docker group
  user:
      name={{ item }}
      group=docker
      state=present
  with_items: docker_users
  when: docker_users is defined
  become: yes

#sudo gpasswd -a ${USER} docker
#sudo gpasswd -a jenkins docker
