
#######
# MAVEN
#

- name: jenkins-slave | Create /opt directory
  file: path=/opt state=directory
  become: yes

#- import_tasks: maven-legacy.yml

#/opt/maven305
- name: jenkins-slave | Set mvn link to Maven 3.5.0
  set_fact: mvn_dir=/opt/maven/apache-maven-3.5.0

- name: jenkins-slave | Display mvn link before
  action: command update-alternatives --display mvn
  changed_when: false
  become: yes
  ignore_errors: true

#TODO
#sudo update-alternatives --remove-all mvn

- name: jenkins-slave | Configure Maven alternatives
  alternatives: name={{ item.name }} link={{ item.link }} path={{ item.path }}
  with_items:
  - { name: mvn, link: /usr/bin/mvn, path: "{{ mvn_dir }}/bin/mvn" }
  when: not( (mvn_dir is undefined) or (mvn_dir is none) or (mvn_dir | trim == '') )
  become: yes

#TODO Verify the symlinks all point to the new mvn location:

#ls -la /etc/alternatives/mvn*
- name: jenkins-slave | Display mvn link after
  action: command update-alternatives --display mvn
  when: not( (mvn_dir is undefined) or (mvn_dir is none) or (mvn_dir | trim == '') )
  changed_when: false  
  become: yes
