---
- name: molecule | Remove molecule
  file: path=/usr/local/bin/molecule state=absent
  when: (( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' ) and ansible_distribution_version is version_compare(19.04, '>='))
  become: true
  ignore_errors: true
  tags: molecule
