---

- import_tasks: python2.yml
- import_tasks: python35.yml
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version not in ['12.04']
# TODO once fixed https://bugs.launchpad.net/ubuntu/+source/python3.6/+bug/1685596
- import_tasks: python36.yml
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version not in ['12.04', '14.04']
#- import_tasks: python37.yml
#  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version not in ['12.04', '14.04']

# BELOW IS WRONG on docker image
# - import_tasks: python-link.yml
