
- include: python2.yml
- include: python3.yml

- name: jenkins-slave | Install python check tools
  pip: name={{ item }}
  with_items:
    - pylint
    - flake8
    - autopep8 #autopep8 py_file --in-place
    - pre-commit #See http://pre-commit.com/
  become: yes

- name: jenkins-slave | Install devops tools for release notes
  pip: name={{ item }}
  with_items:
    - numpy
    - pandas
    - stashy
    - jira #See https://pypi.python.org/pypi/jira/
    - openpyxl
    - "docopt==0.6.2"
  become: yes

- name: jenkins-slave | Install devops tools for ansible windows
  #executable=pip{{ python_versions }}
  #pip: name="https://github.com/diyan/pywinrm/archive/df049454a9309280866e0156805ccda12d71c93a.zip" state=present
  pip: name={{ item }}
  with_items:
    - "pywinrm>=0.2.2"
  become: yes

#- name: jenkins-slave | Install devops tools for ansible kerberos
#  pip: name={{ item }}
#  with_items:
#    - python-dev
#    - libkrb5-dev
#    - krb5-user
#  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (ansible_distribution_version not in ['12.04', '14.04', '16.04'])
#  become: yes

- name: jenkins-slave | Install devops tools for ansible
  pip: name={{ item }}
  with_items:
    - ansible-cmdb
    - ansible-lint
  become: yes

- name: jenkins-slave | Install MySQL requirement for sonar
  action: "{{ ansible_pkg_mgr}} name={{ item }} update_cache=yes state={{ jenkins_pkg_state|default('present') }}"
  become: yes
#  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat')
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  with_items:
    - libmysqlclient-dev

- name: jenkins-slave | Install MySQL for sonar
  pip: name={{ item }}
  with_items:
    - MySQL-python
  become: yes

#Issue wiht out of disk space on Ubuntu 16.04
#unity7.log X11 error: BadWindow (invalid Window parameter) Error code: 3, request code: f, minor code: 0
#See disk space issue : http://askubuntu.com/questions/434581/problem-with-cache-upstart
#sudo apt-get purge logrotate
#sudo apt-get install logrotate
#wget https://launchpad.net/ubuntu/+archive/primary/+files/python-cryptography_1.7.1-2_amd64.deb &&
#wget https://launchpad.net/ubuntu/+archive/primary/+files/python-openssl_16.2.0-1_all.deb &&
#sudo dpkg -i --auto-deconfigure python-cryptography_1.7.1-2_amd64.deb && sudo dpkg -i  python-openssl_16.2.0-1_all.deb
#
#rm ~/.cache/upstart/unity7.log
