
- name: python2 | Install python 2 requirement
  action: "{{ ansible_pkg_mgr}} name={{ item }} update_cache=yes state={{ jenkins_pkg_state|default('present') }}"
  become: yes
#  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat')
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  with_items:
    - python-dev
    - python-pip
    - python-dbg

- name: python | Set python link to python version
  set_fact: python_version=2.7

- name: python | Install virtualenv
  action: "{{ ansible_pkg_mgr}} name={{ item }} update_cache=yes state={{ jenkins_pkg_state|default('present') }}"
  become: yes
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (ansible_distribution_version not in ['12.04', '13.04', '14.04', '15.04'])
  with_items:
    - python-virtualenv
    - virtualenv
#    - virtualenvwrapper

- name: python | Install python check tools
  pip: name={{ item }}
  executable: pip{{ python_version }}
  with_items:
    - pylint
    - flake8
    - autopep8 #autopep8 py_file --in-place
    - pre-commit #See http://pre-commit.com/
  become: yes
  ignore_errors: true

- name: python | Install aws tools
  pip: name={{ item }}
  executable: pip{{ python_version }}
  with_items:
    - awscli
  ignore_errors: true
  become: yes

- name: python | Install devops tools for jobs-duration-charts-admin
  pip: name={{ item }}
  executable: pip{{ python_version }}
  with_items:
 #   - urllib
 #   - cairosvg
    - pygal
    - urllib3[secure]
    - certifi
  become: yes

- name: python | Install devops tools
  pip: name={{ item }}
  executable: pip{{ python_version }}
  with_items:
    - gprof2dot
    - termcolor
    - ansicolors
    - colorama
  become: yes

- name: python | Install devops tools for release notes
  pip: name={{ item }}
  executable: pip{{ python_version }}
  with_items:
    - numpy
    - pandas
    - stashy
    - jira #See https://pypi.python.org/pypi/jira/
    - openpyxl
    - "docopt==0.6.2"
  become: yes
  ignore_errors: true

- name: python | Install devops tools for ansible windows
  #pip: name="https://github.com/diyan/pywinrm/archive/df049454a9309280866e0156805ccda12d71c93a.zip" state=present
  pip: name={{ item }}
  executable: pip{{ python_version }}
  with_items:
    - "pywinrm>=0.2.2"
  become: yes

- name: python | Install devops tools for ansible accelerate mode
  #pip: name="https://github.com/diyan/pywinrm/archive/df049454a9309280866e0156805ccda12d71c93a.zip" state=present
  pip: name={{ item }}
  executable: pip{{ python_version }}
  with_items:
    - python-keyczar
  become: yes
  ignore_errors: true

#sudo apt-get install krb5-kdc krb5-admin-server

- name: python | Install devops tools for ansible kerberos
  pip: name={{ item }}
  executable: pip{{ python_version }}
  with_items:
    - python-dev
    - libkrb5-dev
    - krb5-user
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (ansible_distribution_version not in ['12.04', '14.04', '16.04'])
  become: yes
  ignore_errors: true

- name: python | Install devops tools for ansible
  pip: name={{ item }}
  executable: pip{{ python_version }}
  with_items:
    - ansible-cmdb
    - ansible-lint
  become: yes
  ignore_errors: true

- name: python | Install zabbix tools
  pip: name={{ item }}
  executable: pip{{ python_version }}
  with_items:
    - zabbix-api
    - zabbix-proxy-mysql
  become: yes
  ignore_errors: true

- name: python | Install MySQL requirement for sonar
  action: "{{ ansible_pkg_mgr}} name={{ item }} update_cache=yes state={{ jenkins_pkg_state|default('present') }}"
  become: yes
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  with_items:
    - libmysqlclient-dev

#WARNING need gcc/cpp, must be done after gcc.yml
- name: python | Install MySQL for sonar
  pip: name={{ item }}
  executable: pip{{ python_version }}
  with_items:
    - MySQL-python
  become: yes
  ignore_errors: true

#WARNING need gcc/cpp, must be done after gcc.yml
- name: python | Install ODBC for FreeTDS
  pip: name={{ item }}
  executable: pip{{ python_version }}
  with_items:
    - pyodbc
  become: yes
  ignore_errors: true

#Issue wiht out of disk space on Ubuntu 16.04
#unity7.log X11 error: BadWindow (invalid Window parameter) Error code: 3, request code: f, minor code: 0
#See disk space issue : http://askubuntu.com/questions/434581/problem-with-cache-upstart
#sudo apt-get purge logrotate
#sudo apt-get install logrotate
#wget https://launchpad.net/ubuntu/+archive/primary/+files/python-cryptography_1.7.1-2_amd64.deb &&
#wget https://launchpad.net/ubuntu/+archive/primary/+files/python-openssl_16.2.0-1_all.deb &&
#sudo dpkg -i --auto-deconfigure python-cryptography_1.7.1-2_amd64.deb && sudo dpkg -i  python-openssl_16.2.0-1_all.deb
#
#rm ~/.cache/upstart/unity7.log

- name: python | Install tox for testing python
  pip: name={{ item }}
  executable: pip{{ python_version }}
  with_items:
    - tox
  become: yes
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (ansible_distribution_version not in ['12.04', '13.04', '14.04', '15.04'])
