
#TODO on RedHat add python3.5 by hand

#TODO RedHat https://www.tecmint.com/install-python-in-linux/ install python 3.5 for ansible
#yum -y groupinstall development
#yum -y install zlib-devel

# wget https://www.python.org/ftp/python/3.5.5/Python-3.5.5.tgz
# tar xzf Python-3.5.5.tgz
# cd Python-3.5.5
# ./configure --enable-optimizations
# make altinstall
# cd ..
# rm -f Python-3.5.5.tgz

# which python3
# python3 -V
# python3.5 -V

#virtualenv py3-ansible -p /usr/local/bin/python3.5

- name: python3 | Set python link to python version
  set_fact: python_version=3.5

#- name: python3 | Run pip check
#  shell: (pip -V && pip3.5 -V) | uniq
#  become: yes
#  ignore_errors: true

- name: python3 | Gather current pip3.5 requirement
  shell: "pip{{ python_version }} freeze > requirements-{{ python_version }}.txt"
  when: not( (python_version is undefined) or (python_version is none) or (python_version | trim == '') )
  changed_when: false
  become: yes

- name: python3 | Install missing pip3.5 requirement
  shell: "pip{{ python_version }} install -r requirements-current-{{ python_version }}.txt"
  changed_when: false
  become: yes
#TODO automation
#For now below will be done by hand
  ignore_errors: true
