---

#- import_tasks: python2.yml
#  when: ((ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version is version_compare(18.04, '<=')) and python_enabled
#  tags:
#    - venv
#    - python2

- import_tasks: python35.yml
  when: ((ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version is version_compare(16.04, '<=')) and python_enabled
  tags:
    - venv
    - python35

# TODO once fixed https://bugs.launchpad.net/ubuntu/+source/python3.6/+bug/1685596
- import_tasks: python36.yml
  when: ((ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version is version_compare(18.04, '<=')) and python_enabled
  tags:
    - venv
    - python36

- import_tasks: python37.yml
  when: ((ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version is version_compare(18.04, '>=')) and python_enabled
  tags:
    - virtualenv
    - python37

- import_tasks: python38.yml
  when: ((ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version is version_compare(18.04, '>=')) and python_enabled
  tags:
    - virtualenv
    - python38

#- name: python3 | Set python link to python version
#  set_fact: python3_default_version=3.7

#ln -s /usr/bin/python3.7 /usr/bin/python3 --force
- name: python | Normalize python3 version
  file: path=/usr/bin/python3 src=/usr/bin/python{{ python3_default_version }} state=link force=yes
  become: true
#  ignore_errors: true

#sudo update-alternatives --remove-all python

# update-alternatives --install /usr/bin/python python /usr/bin/python2.6  5
# update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
# update-alternatives --install /usr/bin/python python /usr/bin/python3.5 20

#sudo update-alternatives --config python
