---

#- import_tasks: python2.yml
#  when: ((ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version is version_compare(18.04, '<=')) and python_enabled
#  tags:
#    - venv
#    - python2

- import_tasks: python35.yml
  when: ((ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version is version_compare(16.04, '<=')) and python_enabled
  tags:
    - venv
    - python35

# TODO once fixed https://bugs.launchpad.net/ubuntu/+source/python3.6/+bug/1685596
- import_tasks: python36.yml
  when: ((ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version is version_compare(18.04, '<=')) and python_enabled
  tags:
    - venv
    - python36

- import_tasks: python37.yml
  when: ((ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version is version_compare(18.04, '>=')) and python_enabled
  tags:
    - virtualenv
    - python37

- import_tasks: python38.yml
  when: ((ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version is version_compare(18.04, '>=')) and python_enabled
  tags:
    - virtualenv
    - python38

