
#TODO on RedHat add python3.6 by hand

#TODO RedHat https://www.tecmint.com/install-python-in-linux/ install python 3.6 for ansible
#yum -y groupinstall development
#yum -y install zlib-devel

# wget https://www.python.org/ftp/python/3.6.3/Python-3.6.3.tar.xz
# tar xJf Python-3.6.3.tar.xz
# cd Python-3.6.3
# ./configure
# make
# make install
#rm Python-3.6.3.tgz

# which python3
# python3 -V
# python3.6.3 -V

#virtualenv py3-ansible -p /usr/local/bin/python3.6

- name: python3 | Set python link to python version
  set_fact: python_version=3.6

- name: python3 | Install python 3 requirement
  action: "{{ ansible_pkg_mgr}} name={{ item }} update_cache=yes state={{ jenkins_pkg_state|default('present') }}"
  become: yes
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (ansible_distribution_version not in ['12.04', '14.04'])
  with_items:
    - python3-dev
    - python3-pip
    - python3.6
    - python3.6-dbg
    - idle-python3.6

- name: python3 | Install missing pip3.6 requirement
  shell: "curl https://bootstrap.pypa.io/get-pip.py | sudo python3.6"
  register: curl_result
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (ansible_distribution_version not in ['12.04', '14.04'])
  changed_when: false
  become: yes

#python3.6 -m pip install --user pipenv

#- debug: msg="{{ curl_result.stdout }}"

- name: python3 | Run pip check
  shell: (pip - && pip3.6 -V) | uniq
  when: curl_result.changed
  become: yes
  ignore_errors: true

#- name: python3 | Install devops tools requirements
#  executable=pip{{ python_version }}
#  pip: name={{ item }}
#  with_items:
#    - "pywinrm>=0.2.2"
#  become: yes

- name: python3 | Gather current pip3.6 requirement
  shell: "pip{{ python_version }} freeze > requirements-{{ python_version }}.txt"
  when: not( (python_version is undefined) or (python_version is none) or (python_version | trim == '') )
  changed_when: false
  become: yes

- name: python3 | Install missing pip3.6 requirement
  shell: "pip{{ python_version }} install -r requirements-current-{{ python_version }}.txt"
  changed_when: false
  become: yes
#TODO automation
#For now below will be done by hand
  ignore_errors: true
