---

- name: python3 | Install python (RedHat and CentOS based)
  yum:
    name: "{{ item }}"
    state: "{{ util_pkg_state | default('present') }}"
  when: ((ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat') and ansible_distribution_major_version == '6')
  with_items:
    - "https://centos6.iuscommunity.org/ius-release.rpm"
    - python38u
    - python38u-devel
    - python38u-pip
  become: true

- name: python3 | Install python (RedHat and CentOS based)
  yum:
    name: "{{ item }}"
    state: "{{ util_pkg_state | default('present') }}"
  when: ((ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat') and ansible_distribution_major_version == '7')
  with_items:
    - "https://centos7.iuscommunity.org/ius-release.rpm"
    - python38u
    - python38u-devel
    - python38u-pip
  become: true

- name: python3 | Set python link to python version
  set_fact: python3_version=3.8

- name: python3 | Install python 3 requirement
  action: "{{ ansible_pkg_mgr }} name={{ item }} update_cache=yes state={{ util_pkg_state | default('present') }}"
  become: true
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (ansible_distribution_version not in ['12.04', '14.04'])
  with_items:
    - python
    - python-dev
    - python-dbg
    - python-gdbm

- name: python3 | Run pip check   # noqa 503
  shell: (pip -V && pip -V) | uniq
  when: curl_result.changed
  become: true
#  ignore_errors: true

- name: python3 | Upgrade setuptools
  command: "pip{{ python3_version }} uninstall setuptools{{ python3_version }}"
  changed_when: false
  become: true
  ignore_errors: true
