
#sudo apt-get install apt-transport-https ca-certificates
#See https://docs.docker.com/engine/installation/linux/ubuntulinux/

- name: jenkins-slave | Install security basic tools for Ansible check
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ jenkins_pkg_state|default('present') }}  update_cache=yes"
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  with_items:
    - chkrootkit
  become: yes
  ignore_errors: true

- name: jenkins-slave | Install security basic tools
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ jenkins_pkg_state|default('present') }}  update_cache=yes"
  #when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  #when: (ansible_distribution == 'MacOSX' or ansible_distribution == 'FreeBSD')     
  #when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')  
  with_items:
    - rkhunter
  become: yes
  ignore_errors: true
  
- name: jenkins-slave | Install security basic tools
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ jenkins_pkg_state|default('present') }}  update_cache=yes"
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') or (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')  
  with_items:
    - unhide
  become: yes
  ignore_errors: true
  
- name: jenkins-slave | Install security basic tools for openscap check
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ jenkins_pkg_state|default('present') }}  update_cache=yes"
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  with_items:
    - libopenscap8
    - python-openscap
  become: yes
  ignore_errors: true
  
