
#export WORKSPACE="/root/"
#ON OSX cd /var/root
#cd ${WORKSPACE}
#wget http://alm-sonar.misys.global.ad/static/cpp/build-wrapper-linux-x86.zip --no-check-certificate
#wget http://alm-sonar.misys.global.ad/static/cpp/build-wrapper-macosx-x86.zip --no-check-certificate
#unzip build-wrapper-*-x86.zip
#mkdir -p /usr/local/sonar-build-wrapper/bin/
#cp ${WORKSPACE}/build-wrapper-*-x86/* /usr/local/sonar-build-wrapper/bin/

- name: Ensure unzip is installed.
  package: name=unzip state=present

- name: Download and expand C++ sonar build-wrapper.
  unarchive:
    src: "{{ sonar_build_wrapper_download_url }}"
    dest: "{{ workspace }}"
    copy: no
    creates: /usr/local/sonar-build-wrapper/bin/
  become: yes

- name: Move sonar-build-wrapper into place.
  shell: >
    mv {{ workspace }}/{{ sonar_build_wrapper_expanded_file }}
    creates=/usr/local/sonar-build-wrapper/bin/sonar-build-wrapper

- name: jenkins-slave | Copy sonar runner configuration
  copy: src=sonar-runner-nabla-cpp.properties dest={{ jenkins_slave_home }}/sonar-runner.properties backup=yes owner={{ jenkins_user }} group={{ jenkins_group }}
  changed_when: false
  become: yes
  ignore_errors: true
  