---

- name: jenkins-ssh | Install ssh-askpass when doing git clone on custom repo (for pre-commit-hooks)
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state | default('present') }} update_cache=yes"
  with_items:
    - ssh-askpass
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  become: true

- name: jenkins-ssh | Assert that .ssh directory is present
  file:
    dest: "{{ jenkins_home }}/.ssh"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0700

- name: jenkins-ssh | Copy private key for jenkins
  copy:
    src: "{{ jenkins_ssh_key_file }}"
    dest: "{{ jenkins_home }}/.ssh/id_rsa"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0600
  when: jenkins_ssh_key_file | length > 0
  become: true
  become_user: "{{ jenkins_user }}"
  ignore_errors: true

- name: jenkins-ssh | Copy public key for jenkins
  copy:
    src: "{{ jenkins_ssh_key_file }}.pub"
    dest: "{{ jenkins_home }}/.ssh/id_rsa.pub"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0600
  when: jenkins_ssh_key_file | length > 0
  become: true
  become_user: "{{ jenkins_user }}"
  ignore_errors: true

- name: jenkins-ssh | Check private key for jenkins
  stat:
    path: "{{ jenkins_home }}/.ssh/id_rsa"
  become: true
  become_user: "{{ jenkins_user }}"
  register: key

- debug:
    msg: '{{ key.stat }}'

- name: jenkins-ssh | Create private key for jenkins
  command: no n | /usr/bin/ssh-keygen -f {{ jenkins_home }}/.ssh/id_rsa -t rsa -N ''
  when: not key.stat.exists
  become: true
  become_user: "{{ jenkins_user }}"
  ignore_errors: true

- name: jenkins-ssh | Copy private key
  copy:
    src: "{{ jenkins_ssh_key_file }}"
    dest: "{{ jenkins_home }}/.ssh/id_rsa"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0600
  when: jenkins_ssh_key_file | length > 0
  become: true
  ignore_errors: true

- name: jenkins-ssh | Copy public key
  copy:
    src: "{{ jenkins_ssh_key_file }}.pub"
    dest: "{{ jenkins_home }}/.ssh/id_rsa.pub"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0600
  when: jenkins_ssh_key_file | length > 0
  become: true
  ignore_errors: true

- name: jenkins-ssh | Check private key for jenkins
  stat:
    path: "{{ jenkins_home }}/.ssh/id_rsa"
  register: key

- debug:
    msg: '{{ key.stat }}'

- name: jenkins-ssh | Create private key
  command: no n | /usr/bin/ssh-keygen -f $HOME/.ssh/id_rsa -t rsa -N ''
  when: not key.stat.exists
  become: true
  ignore_errors: true

- name: jenkins-ssh | Setup SSH authorized keys
  lineinfile:
    line: "{{ item }}"
    insertafter: EOF
    state: present
    create: true
    mode: 0600
    dest: "{{ jenkins_home }}/.ssh/authorized_keys"
    owner: "{{ jenkins_user }}"
  with_items: "{{ jenkins_ssh_authorized_keys_fingerprints }}"
  when: jenkins_ssh_authorized_keys_fingerprints | length > 0
  become: true
  become_method: sudo
  tags:
    - never
    - generic
    - support

- name: jenkins-ssh | Setup SSH hosts
  lineinfile:
    line: "{{ item }}"
    insertafter: EOF
    state: present
    create: true
    mode: 0644
    dest: "{{ jenkins_home }}/.ssh/known_hosts"
    owner: "{{ jenkins_user }}"
  with_items: "{{ jenkins_ssh_fingerprints }}"
  when: jenkins_ssh_fingerprints | length > 0
  become: true
  tags:
    - fingerprints
