---

- file: dest={{jenkins_home}}/.ssh state=directory

- name: jenkins-ssh | Copy private key
  copy: >
    src={{jenkins_ssh_key_file}}
    dest={{jenkins_home}}/.ssh/id_rsa
    owner={{jenkins_user}}
    group={{jenkins_group}}
    mode=0600
  register: key
  when: jenkins_ssh_key_file != ""
  become: yes
  ignore_errors: yes

- name: jenkins-ssh | Create private key
  command: /usr/bin/ssh-keygen -A
  when: key|failed
  become: yes

- name: jenkins-ssh | Copy private key for jenkins
  copy: >
    src={{jenkins_ssh_key_file}}
    dest={{jenkins_home}}/.ssh/id_rsa
    owner={{jenkins_user}}
    group={{jenkins_group}}
    mode=0600
  register: key
  when: jenkins_ssh_key_file != ""
  become_user: "{{ jenkins_user }}"
  ignore_errors: yes

- name: jenkins-ssh | Create private key for jenkins
  command: /usr/bin/ssh-keygen -A
  when: key|failed
  become_user: "{{ jenkins_user }}"
  ignore_errors: yes
  
- name: jenkins-ssh | Setup SSH hosts
  lineinfile: 
    line="{{item}}"
    insertafter="EOF"
    state="present"
    create="yes"
    mode="0644"
    dest="{{jenkins_home}}/.ssh/known_hosts"
    owner="{{jenkins_user}}"
  with_items: "{{jenkins_ssh_fingerprints}}"
  when: jenkins_ssh_fingerprints | length > 0    
  become: yes 

- name: jenkins-ssh | Setup SSH authorized keys
  lineinfile: 
    line="{{item}}"
    insertafter="EOF"
    state="present"
    create="yes"
    mode="0600"
    dest="{{jenkins_home}}/.ssh/authorized_keys"
    owner="{{jenkins_user}}"
  with_items: "{{jenkins_ssh_authorized_keys_fingerprints}}"
  when: jenkins_ssh_authorized_keys_fingerprints | length > 0    
  become: yes
