
#TODO
#http://www.thegeekstuff.com/2013/10/tmpreaper-examples/

- name: jenkins-slave | Install tmpwatch package
  action: "{{ ansible_pkg_mgr}} name='tmpwatch' state={{ jenkins_pkg_state|default('present') }}"
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat')
  become: yes
  ignore_errors: yes
  
- name: jenkins-slave | Install tmpreaper package
  action: "{{ ansible_pkg_mgr}} name='tmpreaper' state={{ jenkins_pkg_state|default('present') }}"
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  become: yes
  ignore_errors: yes

#it adds itself to /etc/cron.daily
#but you need to configure it (comment out or remove one line in /etc/tmpreaper.conf #SHOWWARNING=true
- name: jenkins-slave | Enable tmpreaper package
  lineinfile: dest=/etc/tmpreaper.conf line='SHOWWARNING=true' regexp='^#SHOWWARNING=true'
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  become: yes
  ignore_errors: yes
  changed_when: false

- name: jenkins-slave | Add sanitary job in cron
  cron: name="tmp cleanup" hour="1" minute="0" job="find /tmp -user {{ jenkins_user }} -atime +7 -exec rm -rf {} +" user={{ jenkins_user }}
  become: yes
  ignore_errors: true
  tags: cron
#sudo service cron restart

#Fix jetty filling tmp
- name: jenkins-slave | Add JAVA_OPTS in /etc/profile
  lineinfile: dest=/etc/profile line="export JAVA_OPTS=-Djava.io.tmpdir=$WORKSPACE/target/tmp" insertafter=EOF
#or ~.bash_profile
  become: yes
  changed_when: false
