
- name: jenkins-slave | Create /opt/zabbix/externalscripts folder
  file: path=/opt/zabbix/externalscripts state=directory owner={{ jenkins_user }} group={{ jenkins_group }} mode=0775
  become: true
  changed_when: false

- name: jenkins-slave | Copy zabbix script (1)
  copy: src=array-all-status-dell.sh dest=/opt/zabbix/externalscripts/array-all-status-dell.sh backup=yes owner={{ jenkins_user }} group={{ jenkins_group }} mode=0755
  become: true
  ignore_errors: true

- name: jenkins-slave | Copy zabbix script (2)
  copy: src=array-all-status-hp.sh dest=/opt/zabbix/externalscripts/array-all-status-hp.sh backup=yes owner={{ jenkins_user }} group={{ jenkins_group }} mode=0755
  become: true
  ignore_errors: true

- name: jenkins-slave | Install open-iscsi package
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ jenkins_pkg_state|default('present') }} update_cache=yes"
  tags: package
  with_items:
   - open-iscsi
  changed_when: false
  become: yes
  ignore_errors: true

- name: jenkins-slave | Copy zabbix script (3)
  copy: src=iscsi-status.sh dest=/opt/zabbix/externalscripts/iscsi-status.sh backup=yes owner={{ jenkins_user }} group={{ jenkins_group }} mode=0755
  become: true
  ignore_errors: true

- name: jenkins-slave | Copy zabbix script (4)
  copy: src=fs-discovery.sh dest=/opt/zabbix/externalscripts/fs-discovery.sh backup=yes owner={{ jenkins_user }} group={{ jenkins_group }} mode=0755
  become: true
  ignore_errors: true

- name: jenkins-slave | Copy zabbix script (5)
  copy: src=zpool-status.sh dest=/opt/zabbix/externalscripts/zpool-status.sh backup=yes owner={{ jenkins_user }} group={{ jenkins_group }} mode=0755
  become: true
  ignore_errors: true

- name: jenkins-slave | Copy zabbix script (6)
  copy: src=zpool-discovery.sh dest=/opt/zabbix/externalscripts/zpool-discovery.sh backup=yes owner={{ jenkins_user }} group={{ jenkins_group }} mode=0755
  become: true
  ignore_errors: true

- name: jenkins-slave | Copy zabbix script (7)
  copy: src=zfs-vfs-size.sh dest=/opt/zabbix/externalscripts/zfs-vfs-size.sh backup=yes owner={{ jenkins_user }} group={{ jenkins_group }} mode=0755
  become: true
  ignore_errors: true
