---
dependency:
  name: galaxy
  enabled: true
  options:
    ignore-errors: true
driver:
  name: docker
platforms:
  - name: jenkins-slave-centos
    image: milcom/centos7-systemd:latest
    groups:
      - group1
    privileged: true
  - name: jenkins-slave-debian-jessie
    image: maint/debian-systemd:latest
    groups:
      - group1
    privileged: true
  - name: jenkins-slave-debian-stretch
    image: minimum2scp/systemd-stretch:latest
    command: /sbin/init
    groups:
      - group1
  - name: jenkins-slave-ubuntu-xenial
    image: solita/ubuntu-systemd:xenial
    groups:
      - group1
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
  - name: jenkins-slave-ubuntu-bionic
    image: solita/ubuntu-systemd:bionic
    groups:
      - group1
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
#    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
#  playbooks:
#    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # 2 below will be hard to get 100% right
    # - idempotence
    # - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
