---

- name: Converge
  hosts: zabbix-agent-centos

  roles:
    - role: geerlingguy.repo-epel

- name: Converge
  hosts: all

  roles:
    - role: alban.andrieu.jenkins-slave
      verbose: yes
  no_log: False
