---

- name: Converge
  hosts: jenkins-slave-centos

  roles:
    - role: geerlingguy.repo-epel

- name: Converge
  hosts: all

  roles:
    - role: alban.andrieu.jenkins-slave
      verbose: true
  no_log: false
